include $(THEOS)/makefiles/common.mk

TWEAK_NAME = TwitterNA
TwitterNA_FILES = TwitterNA.xm
TwitterNA_FRAMEWORKS = UIKit
TwitterNA_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/tweak.mk
include $(THEOS)/makefiles/aggregate.mk